### ISSUE TITLE
请问有关网络的问题

### ISSUE THREAD

**Issue by harryisfish** [Press-One/prs-lib-py#2]
使用一下示例代码时，出现报错：
`import prs_lib

client = prs_lib.PRS({
  'env': 'dev',
  'debug': True,
})
res = client.block.get_by_rids([
    'ba03bd584d69b89615ce8db22b4c593342a5ec09b343a7859044a8e4d389c4c2',
    '65163724a98d29506b1031dc68fa62fb5a7a11fe631fb723a723b2a19e9bb65c'
])
print(res.json())`

报错详情：
Traceback (most recent call last):
  File "E:/PRJCT/LEPERone_web/ws_test.py", line 28, in <module>
    '65163724a98d29506b1031dc68fa62fb5a7a11fe631fb723a723b2a19e9bb65c'
  File "C:\_virtualenv\lib\site-packages\prs_lib\block.py", line 27, in get_by_rids
    debug=self.config.debug,
  File "C:\_virtualenv\lib\site-packages\prs_lib\request.py", line 119, in request
    method, url, json=data, timeout=timeout
  File "C:\_virtualenv\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\_virtualenv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\_virtualenv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dev.press.one', port=443): Max retries exceeded with url: /api/v2/blocks/ba03bd584d69b89615ce8db22b4c593342a5ec09b343a7859044a8e4d389c4c2,65163724a98d29506b1031dc68fa62fb5a7a11fe631fb723a723b2a19e9bb65c (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CD3C90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

测试用的机子和环境应该都是没有问题的，请问这样的错误有可能是什么原因造成的呢？

**Comment by harryisfish** [comment]
试了一下官方给的正式环境就可以正常取得报文，测试环境就一直报这个错

**Comment by zh4n7wm** [comment]
应该是前两天测试环境服务不稳定导致的；你有空可以再试试看？

**Comment by zh4n7wm** [comment]
已经没有问题了
